typography_spectrum: 0.8080337
color:
  saturation: 0.1741664
  lightness: 0.6252754
  brandStrength: 0.05297514
  rhythmicContrast: 0.1450003
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
layout_spectrum: 0.1212068
name: wide
navigation: []
title: Wide
description: Simplify IT Complexity
