collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 0
  lightness: 1
  brandColors:
    - '#1D1D1B'
    - '#DEDEDE'
    - '#656B69'
    - '#74120C'
    - '#E80211'
  rhythmicContrast: 0
typography_spectrum: 0.4636194
layout_spectrum: 0.734767
name: wide
