typography_spectrum: 0.8080337
color:
  saturation: 0.1741664
  lightness: 0.6252754
  brandStrength: 0.05297514
  rhythmicContrast: 0.1450003
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
layout_spectrum: 0.1212068
name: wide
navigation:
  - name: aa
    id: 5aef39a3-610f-4379-a4ce-3243f5aad797
    type: content
  - name: Vietnam
    id: 5d33ed3b-c770-40aa-b136-0089685e96e7
    type: content
title: Wide
description: Simplify IT Complexity
