collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.7402052
  brandStrength: 0.9333022
  lightness: 0.6515858
  brandColors:
    - '#1D1D1B'
    - '#DEDEDE'
    - '#656B69'
    - '#74120C'
    - '#E80211'
  rhythmicContrast: 0.8232276
typography_spectrum: 0.4636194
layout_spectrum: 0.02425373
name: wide
navigation:
  - name: SIMPLIFY IT
    id: 5e759759-266a-4fd5-9f6d-76f0fee315a7
    type: content
